country = [{id:"al",name:"Albania"},
{id:"dz",name:"Algeria"},
{id:"ar",name:"Argentina"},
{id:"am",name:"Armenia"},
{id:"au",name:"Australia"},
{id:"at",name:"Austria"},
{id:"bh",name:"Bahrain"},
{id:"bd",name:"Bangladesh"},
{id:"by",name:"Belarus"},
{id:"be",name:"Belgium"},
{id:"bj",name:"Benin"},
{id:"bo",name:"Bolivia"},
{id:"bw",name:"Botswana"},
{id:"br",name:"Brazil"},
{id:"bn",name:"Brunei Darussalam"},
{id:"bg",name:"Bulgaria"},
{id:"bf",name:"Burkina Faso"},
{id:"kh",name:"Cambodia"},
{id:"cm",name:"Cameroon"},
{id:"ca",name:"Canada"},
{id:"td",name:"Chad"},
{id:"cl",name:"Chile"},
{id:"cn",name:"China"},
{id:"co",name:"Colombia"},
{id:"cg",name:"Congo"},
{id:"cd",name:"Congo DRC"},
{id:"cr",name:"Costa Rica"},
{id:"ci",name:"Cote d'Ivoire"},
{id:"hr",name:"Croatia"},
{id:"cz",name:"Czech Republic"},
{id:"dk",name:"Denmark"},
{id:"do",name:"Dominican Republic"},
{id:"ec",name:"Ecuador"},
{id:"eg",name:"Egypt"},
{id:"ee",name:"Estonia"},
{id:"et",name:"Ethiopia"},
{id:"fi",name:"Finland"},
{id:"fr",name:"France"},
{id:"ga",name:"Gabon"},
{id:"ge",name:"Georgia"},
{id:"de",name:"Germany"},
{id:"gh",name:"Ghana"},
{id:"gr",name:"Greece"},
{id:"gt",name:"Guatemala"},
{id:"hu",name:"Hungary"},
{id:"in",name:"India"},
{id:"id",name:"Indonesia"},
{id:"iq",name:"Iraq"},
{id:"ie",name:"Ireland"},
{id:"il",name:"Israel"},
{id:"it",name:"Italy"},
{id:"jp",name:"Japan"},
{id:"jo",name:"Jordan"},
{id:"kz",name:"Kazakhstan"},
{id:"ke",name:"Kenya"},
{id:"kw",name:"Kuwait"},
{id:"kg",name:"Kyrgyzstan"},
{id:"la",name:"Laos"},
{id:"lv",name:"Latvia"},
{id:"lt",name:"Lithuania"},
{id:"my",name:"Malaysia"},
{id:"ml",name:"Mali"},
{id:"mt",name:"Malta"},
{id:"mr",name:"Mauritania"},
{id:"mu",name:"Mauritius"},
{id:"mx",name:"Mexico"},
{id:"md",name:"Moldova"},
{id:"mn",name:"Mongolia"},
{id:"ma",name:"Morocco"},
{id:"mz",name:"Mozambique"},
{id:"mm",name:"Myanmar"},
{id:"na",name:"Namibia"},
{id:"np",name:"Nepal"},
{id:"nl",name:"Netherlands"},
{id:"nz",name:"New Zealand"},
{id:"ni",name:"Nicaragua"},
{id:"ne",name:"Niger"},
{id:"ng",name:"Nigeria"},
{id:"no",name:"Norway"},
{id:"pk",name:"Pakistan"},
{id:"ps",name:"Palestine"},
{id:"pa",name:"Panama"},
{id:"pg",name:"Papua New Guinea"},
{id:"py",name:"Paraguay"},
{id:"pe",name:"Peru"},
{id:"ph",name:"Philippines"},
{id:"pl",name:"Poland"},
{id:"pt",name:"Portugal"},
{id:"qa",name:"Qatar"},
{id:"ro",name:"Romania"},
{id:"ru",name:"Russia"},
{id:"rw",name:"Rwanda"},
{id:"sa",name:"Saudi Arabia"},
{id:"sn",name:"Senegal"},
{id:"rs",name:"Serbia"},
{id:"sl",name:"Sierra Leone"},
{id:"sg",name:"Singapore"},
{id:"sk",name:"Slovakia"},
{id:"za",name:"South Africa"},
{id:"kr",name:"South Korea"},
{id:"es",name:"Spain"},
{id:"lk",name:"Sri Lanka"},
{id:"se",name:"Sweden"},
{id:"ch",name:"Switzerland"},
{id:"tw",name:"Taiwan"},
{id:"tz",name:"Tanzania"},
{id:"th",name:"Thailand"},
{id:"gm",name:"The Gambia"},
{id:"tg",name:"Togo"},
{id:"tn",name:"Tunisia"},
{id:"tr",name:"Turkey"},
{id:"ug",name:"Uganda"},
{id:"ua",name:"Ukraine"},
{id:"ae",name:"United Arab Emirates"},
{id:"gb",name:"United Kingdom"},
{id:"us",name:"United States"},
{id:"uy",name:"Uruguay"},
{id:"ve",name:"Venezuela"},
{id:"vn",name:"Vietnam"},
{id:"ye",name:"Yemen"},
{id:"zm",name:"Zambia"},
{id:"zw",name:"Zimbabwe"}];
